### ISSUE TITLE
weewx isn't updating the index page with latest updates

### ISSUE THREAD

**Issue by louking** [louking/weather#31]
https://github.com/weewx/weewx/wiki/Troubleshooting-the-Davis-Vantage-station#corrupt-station-memory

Seeing the following in the log

```
Dec 13 06:18:07 rasp-server-1 weewx[3641] DEBUG weewx.drivers.vantage: DMPAFT complete: page timestamp ******* N/A *******     (    N/A   ) less than final timestamp 2021-12-12 16:30:00 EST (1639344600)
```

**Comment by louking** [comment]
Corrected with 

```
2021-12-13 06:35 sudo bin/wee_device --clear-memory [this resolved problem; data lost between 2021-12-12 14:30 and 2021-12-13 06:40]
2021-12-13 06:33 sudo bin/wee_device --dump [seeing CRC errors]
		Dec 13 06:29:59 rasp-server-1 weewx[3724] DEBUG weewx.drivers.vantage: Get_data_with_crc16; try #1 failed. CRC error
		Dec 13 06:29:59 rasp-server-1 weewx[3724] ERROR weewx.drivers.vantage: Unable to pass CRC16 check while getting data
		Dec 13 06:34:34 rasp-server-1 wee_device[3743] DEBUG weewx.drivers.vantage: Get_data_with_crc16; try #1 failed. CRC error
		Dec 13 06:34:35 rasp-server-1 wee_device[3743] DEBUG weewx.drivers.vantage: Get_data_with_crc16; try #2 failed. CRC error
		Dec 13 06:34:35 rasp-server-1 wee_device[3743] DEBUG weewx.drivers.vantage: Get_data_with_crc16; try #3 failed. CRC error
		Dec 13 06:34:36 rasp-server-1 wee_device[3743] DEBUG weewx.drivers.vantage: Get_data_with_crc16; try #4 failed. CRC error
		Dec 13 06:34:36 rasp-server-1 wee_device[3743] ERROR weewx.drivers.vantage: Unable to pass CRC16 check while getting data

	   	lking@rasp-server-1:/home/weewx $ sudo bin/wee_device --dump
		Using configuration file /home/weewx/weewx.conf
		Using Vantage driver version 3.2.2 (weewx.drivers.vantage)
		Proceeding will dump all data in the logger.
		Are you sure you want to proceed (y/n)? y
		Starting dump ...
		 Traceback (most recent call last): 2021-12-09 01:50:00 EST (1639032600)
		  File "/home/weewx/bin/wee_device", line 78, in <module>
		    main()
		  File "/home/weewx/bin/wee_device", line 74, in main
		    device.configure(config_dict)
		  File "/home/weewx/bin/weewx/drivers/__init__.py", line 67, in configure
		    self.do_options(options, parser, config_dict, not options.noprompt)
		  File "/home/weewx/bin/weewx/drivers/vantage.py", line 2101, in do_options
		    self.dump_logger(station, config_dict, options.noprompt)
		  File "/home/weewx/bin/weewx/drivers/vantage.py", line 2703, in dump_logger
		    for record in converted_generator:
		  File "/home/weewx/bin/weewx/units.py", line 1682, in __next__
		    _record = next(self.input_generator)
		  File "/home/weewx/bin/weewx/drivers/vantage.py", line 697, in genArchiveDump
		    _page = self.port.get_data_with_crc16(267, prompt=_ack, max_tries=self.max_tries)
		  File "/home/weewx/bin/weewx/drivers/vantage.py", line 230, in get_data_with_crc16
		    raise weewx.CRCError("Unable to pass CRC16 check while getting data")
		weewx.CRCError: Unable to pass CRC16 check while getting data
```
